### ISSUE TITLE
Hide finish drink when there is no drink being drunk

### ISSUE THREAD

**Issue by ghost** [AugustanaCSC490Spring2015/SealTeamSixBACCalculator#13]
This will also prevent the app from crashing when there is no current drink and the user clicks the button

**Comment by caitlinloney** [comment]
Does it have to be hid, or can it just be disabled?

**Comment by caitlinloney** [comment]
I will work on a confirmation dialog for this button

**Comment by chrisschroeder92** [comment]
Currently the backend code checks to make sure its not already finished - a confirmation has been added a few commits ago
