### ISSUE TITLE
Untappd search only uses first word

### ISSUE THREAD

**Issue by chrisschroeder92** [AugustanaCSC490Spring2015/SealTeamSixBACCalculator#22]
For example, searching "bourbon county" yields the same search as "bourbon"

**Comment by ghost** [comment]
The search is actually working correctly for how it is set up, per the API documentation, 
Note: The best way to search is always "Brewery Name + Beer Name", such as "Dogfish 60 Minute".

In the future, we could add more specific parameters to the search query, but for the sake of time we will leave it as Untappd default
