### ISSUE TITLE
Sober in label shows negative number once you're sober

### ISSUE THREAD

**Issue by lnicolaysen** [AugustanaCSC490Spring2015/SealTeamSixBACCalculator#27]
Would we maybe just want that to stay there once it reaches 0?

**Comment by lnicolaysen** [comment]
Also, once the current BAC is 0, shouldn't this label also be 0? Right now the BAC could be 0, but the sober in value could be 0.15 or something like that.

**Comment by ghost** [comment]
Christian fixed
